### PR TITLE
1.0

### PR DESCRIPTION
**Pull request by rathishubham7**

### CODE REVIEW

**Comment by MeepyMay** [comment]
@rathishubham7 I did a quick overview. Be careful with the filter feature. We don't need that for Version 1.0. If you go to "Issues" tab, click "Milestones," then "Version 1.0," you'll see all the issues related to the Phase I milestone.

**Comment by rathishubham7** [comment]
ok sure.

**Comment by Xiaodan** [comment]
@rathishubham7 I downloaded all files to my own laptop and found out that you were not using auto-layout. And the icon of My Schedule tab is missing. 
Additionally, some things we discussed with May in our last meeting were not included in the most recent code:
1) On the profile page, the name/title/company should be changeable. 
2) Check the color code used to align with ABI standards.

**Comment by psok** [comment]
@rathishubham7 please use auto-layout to ensure the adaptive UI that responses correctly on different screen sizes

**Comment by psok** [comment]
@rathishubham7 please also investigate and resolve the warnings

**Comment by rathishubham7** [comment]
yes. i removed the constraints in the storyboards because there was some issue with the external framework ( XLPagerTabStrip ). i'll add them ASAP.

**Comment by Xiaodan** [comment]
Looks good to me!

**Pull request merged**
